In [34]:
import numpy as np
from math import comb, factorial
from itertools import combinations_with_replacement
from itertools import permutations

def factl(l):
	return [factorial(i) for i in l]

def permanent(matrix):
    n = len(matrix)
    perm_sum = 0

    for perm in permutations(range(n)):
        product = 1
        for i in range(n):
            product *= matrix[i, perm[i]]
        perm_sum += product

    return perm_sum

def A(lam):
	N = lam.shape[0]
	n = 2
	N_out = comb(N+n-1, n)
	A = np.ones((N_out, N_out))*42

	for idx_n, comb_n in enumerate(combinations_with_replacement(range(N), n)):
		for idx_m, comb_m in enumerate(combinations_with_replacement(range(N), n)):
			n_i = np.zeros(N, dtype=int)
			for x in comb_n:
				n_i[x] += 1
			
			m_i = np.zeros(N, dtype=int)
			for x in comb_m:
				m_i[x] += 1

			omega = []
			for i,x in enumerate(n_i):
				omega.extend([i]*x)
			omega = np.array(omega)

			omegap = []
			for i,x in enumerate(m_i):
				omegap.extend([i]*x)
			omegap = np.array(omegap)

			sub = lam[omegap]
			sub = sub[:, omega]
			prefactor = np.sqrt(np.prod(factl(omega)) * np.prod(factl(omegap)))
			A[idx_m, idx_n] =  prefactor * permanent(sub)
	return A

(6, 6)


In [21]:
lam = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(lam)
A(lam)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 0 0]
[2 0 0]
[0 0]
[0 0]
[[1 2 3]
 [1 2 3]]


4.0